apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment #The name of the Kubernetes Deployment to be created in the Kubernetes cluster
  labels:
    app: BE
spec:
  replicas: 2 #The number of pods to be created in the Kubernetes cluster for the React.js application container
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: app 
    spec:
      containers:
      - name: react-app #The name of the react.js application container
        image: bravinwasike/react-app:latest #The Docker image for building the React.js application container
        ports:
        - containerPort: 8081 #The port for the React.js application   container