apiVersion: v1
kind: Service
metadata:
  name: first-kube-service #The name of the Kubernetes Service to be created in the Kubernetes cluster
  labels:
    app: spring-boot-application 
    type: BE
spec:
  selector:
    app: app
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
  - protocol: HTTP
    port: 8081 #Service port